"""added quotes

Revision ID: 577b33e86d32
Revises: 1ee7d6fca58f
Create Date: 2026-03-14 23:54:18.268803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577b33e86d32'
down_revision: Union[str, Sequence[str], None] = '1ee7d6fca58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_batches',
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='task_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_batches'))
    )
    op.create_index(op.f('ix_quote_batches_status'), 'quote_batches', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('lang', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['quote_batches.id'], name=op.f('fk_quotes_batch_id_quote_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index(op.f('ix_quotes_batch_id'), 'quotes', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_batch_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_quote_batches_status'), table_name='quote_batches')
    op.drop_table('quote_batches')
    # ### end Alembic commands ###
