"""added habbits

Revision ID: 58396348228f
Revises: da932267b6d3
Create Date: 2026-03-05 01:41:51.673549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58396348228f'
down_revision: Union[str, Sequence[str], None] = 'da932267b6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('name', sa.String(length=46), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("schedule_type IN ('daily','weekly_days','monthly_day','yearly_date','interval_cycle')", name='habit_schedule_type_check'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_schedule_type'), 'habits', ['schedule_type'], unique=False)
    op.create_index(op.f('ix_habits_ends_on'), 'habits', ['ends_on'], unique=False)
    op.create_table('habit_completions',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'completed_on', name='uq_habit_completion_habit_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_completions')
    op.drop_index(op.f('ix_habits_ends_on'), table_name='habits')
    op.drop_index(op.f('ix_habits_schedule_type'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
