"""initial_migration

Revision ID: da932267b6d3
Revises:
Create Date: 2025-11-03 17:59:05.016875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da932267b6d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('themes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('name', sa.String(length=46), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        INSERT INTO priorities (id, name, weight, color, created_at, updated_at) VALUES
        ('00000000-0000-0000-0000-000000000001', 'низкий', 1, '#22C55E', NOW(), NOW()),
        ('00000000-0000-0000-0000-000000000002', 'средний', 2, '#EAB308', NOW(), NOW()),
        ('00000000-0000-0000-0000-000000000003', 'высокий', 3, '#EF4444', NOW(), NOW());
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('themes')
    op.drop_table('priorities')
    # ### end Alembic commands ###
